// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkpyxhjxsmpfcezfqllz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcHl4aGp4c21wZmNlemZxbGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTIyNzcsImV4cCI6MjA3MTAyODI3N30.VoV6fSQS2QaqhqRD-AqiJL_iwDUx2Pk_6HAZg4WX_sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});